import type { VendorCategory } from './marketplace-types'

export interface CategorySection {
  id: string
  label: string
  vendorCategory?: VendorCategory
  subcategories: string[]
}

export interface LocationSection {
  id: string
  label: string
  items: string[]
}

export interface FilterSection {
  id: string
  label: string
  items: string[]
}

// Main vendor categories mapped to VendorCategory type, each with subcategories
export const DIRECTORY_CATEGORIES: CategorySection[] = [
  {
    id: 'dj-services',
    label: 'DJ Services',
    vendorCategory: 'wedding_dj',
    subcategories: [
      'Wedding DJ',
      'DJ Prom & School Dances',
      'DJ Latin Music',
      'Wedding DJ and MC',
      'DJ Parties',
      'Karaoke DJ',
      'DJ Lessons',
    ],
  },
  {
    id: 'event-planning',
    label: 'Event Planning',
    vendorCategory: 'wedding_planner',
    subcategories: [
      'Event Planners',
      'Party Planner',
      'Corporate Events',
      'Small Venues & Event Spaces',
      'Catering Services',
      'Wedding Planner',
      'Party Venues',
      'Party Rentals',
      'Wedding Venues',
      'Wedding Planning',
      'Bartender Services',
      'Canopy & Tent Rental',
      'Cheap Wedding Venues',
      'Party Supplies',
      'Birthday Party',
      'Party Equipment Rentals',
      'Wedding',
      'Cheap Venues & Event Spaces',
      'Cheap Banquet Halls',
      'Kids Birthday Places',
      'Dinnerware Rental',
      'Kids Birthday Party',
      'Affordable Wedding Venues',
      'Corporate Event Venues',
      'Photo Booth Rentals',
      'All Inclusive Wedding Packages',
      'Chair And Table Rentals',
      'Party Decorations',
      'Bartenders',
      'Dance Floor Rental',
      'Outdoor Venues & Event Spaces',
      'Team Building Activities',
      'Birthday Party Venues',
      'Bounce House Rental',
      'Party Catering',
      'Private Party Venues',
      'Wedding Catering',
      'Bounce House Rentals',
      'Small Party Catering',
      'Bridal Shower',
      'Outdoor Event Space',
      'Tea Party',
      'Banquet Halls For Rent',
      'Party',
      'Birthday Party Planner',
      'Party Rental Space',
      'Baby Shower Decorations',
      'Party Halls',
      'Birthday',
    ],
  },
  {
    id: 'venues',
    label: 'Venues',
    vendorCategory: 'wedding_venue',
    subcategories: [
      'Outdoor Event Space',
      'Party Venues & Function Rooms',
      'Outdoor Venues & Event Spaces',
      'Small Venues & Event Spaces',
      'Birthday Party Venues',
      'Party Rental Space',
      'Party Equipment Rentals',
      'Private Party Venues',
      'Cheap Banquet Halls',
      'Event Venues',
      'Party Venues',
      'Cheap Venues & Event Spaces',
      'Cheap Banquet Halls for Rent',
      'Rooftop Restaurant',
      'Outdoor Venues',
      'Outdoor Bar',
      'Venue',
      'Birthday Parties',
      'Cheap Halls for Rent',
      'Outdoor Dining',
      'Wedding Planning',
      'Wedding',
      'Kids Birthday Party',
      'Private Parties',
      'Concert Venues',
      'Karaoke Bars',
      'Birthday',
      'Venues and Event Spaces',
      'Wedding Venues',
      'Hall Rental',
      'Small Party Venue',
      'Halls for Rent',
      'Banquet Halls',
      'Small Private Party Venues',
      'Corporate Event Venues',
      'Baby Shower Venues',
      'Wedding Reception Venues',
      'Small Wedding Venues',
      'Banquet Halls for Rent',
      'Affordable Wedding Venues',
      'Cheap Wedding Venues',
      'Bridal Shower Venues',
      'Venues',
      'Restaurants With Private Party Rooms',
      'Holiday Party Venue',
      'Restaurants With Private Rooms',
      'Shared Office Spaces',
      'Engagement',
    ],
  },
  {
    id: 'bars-clubs',
    label: 'Bars & Clubs',
    vendorCategory: 'bar_club',
    subcategories: [
      'Wine Bars',
      'Irish Pub',
      'Beer Bar',
      'Dive Bars',
      'Gay Bars',
      'Karaoke Bars',
      'Happy Hour',
      'Beer Gardens',
      'Bottomless Mimosa Brunch',
      'Craft Beer',
      'Happy Hour Specials',
      'Outdoor Bar',
      'Pubs',
      'Pubs and Bars With Food',
      'Cocktail Bars',
      'Bottomless Mimosas',
      'Fish & Chips',
      'Speakeasy Bars',
      'Speakeasy',
      'Brunch',
      'Bar and Grill',
      'Breweries',
      'Steakhouses',
      'Lounges',
    ],
  },
  {
    id: 'restaurant-food',
    label: 'Restaurant & Food',
    subcategories: [
      'Pasta',
      'Romantic Restaurant',
      'Italian',
      'Vegetarian Food',
      'Sunday Brunch',
      'Oysters',
      'Gluten Free Restaurants',
      'Seafood',
      'Lounges',
      'Soup',
      'Salad',
      'French Restaurant',
      'Wineries',
      'Indian Food',
      'Diners',
      'Bar Food',
      'Bowling',
      'Vegan Breakfast',
      'Ceviche',
      'Appetizers',
      'Rooftop Restaurant',
      'Vegan Restaurants',
      'Dinner and Drinks',
      'Ice Cream',
      'Patio Dining',
      'Mediterranean Food',
      'Foodie Restaurants',
      'Bars for Mature Singles',
      'Bars With Outdoor Seating',
      'Beach Bars',
      'Breakfast',
      'Brunch Reservations',
      'Buffalo Chicken Wrap',
      'Chicken Caesar Wrap',
      'Cocktails',
      'Farmers Market',
      'Free Live Music',
      'Froyo',
      'Frozen Drinks',
      'Graduation Dinner',
      'Hip New Restaurants',
      'Home Cooking Restaurant',
      'Japanese Bakery',
      'Karaoke',
      'Kid Friendly Bars',
      'Late Night Food',
      'Mango Sticky Rice',
      'Martini',
      'Open Mic',
      'Pizza Food Truck',
      'Poke',
      'Pool Table Bar',
      'Pulled Pork Sandwich',
      'Shawarma',
      'Singles Scene',
      'Soft Serve Ice Cream',
      'Spinach Artichoke Dip',
      'Steamed Crabs',
      'Weekend Happy Hour',
      'Barbeque',
      'Beer Gardens',
      'Bratwurst',
      'Brunch',
      'Custom Cookies',
      'Food Trucks',
      'Hot Dogs',
      'Ice Cream & Frozen Yogurt',
      'New Mexican Cuisine',
      'Shaved Ice',
      'Brewery Tour',
      'Comedy Clubs',
      'Jazz Club',
      'Trivia Night',
      'Gambling Casinos',
      'Open Late',
      'Rooftop Pool Parties',
    ],
  },
  {
    id: 'fine-dining',
    label: 'Fine Dining',
    subcategories: [
      'American Bistro',
      'Farm to Table Restaurants',
      'Wine Bars',
      'Vegetarian Food',
      'Date Night Restaurant',
      'Craft Cocktails',
      'Gastropubs',
      'Tasting Menu',
      'Small Plates',
      'Fusion Restaurant',
      'Tapas Bars',
      "Chef's Table",
      'Prix Fixe Menu',
      'Outdoor Patio Dining',
      'Craft Burger',
      'Breakfast',
      'Brunch',
      'Restaurants With Private Party Rooms',
      'Fine Dining',
      'Happy Hour',
      'Unique Fun Dining Events',
      'Sunday Brunch',
      'Restaurants',
      'Unique Restaurants',
      'Dinner Restaurant',
      'Kid Friendly Restaurant',
      'Outdoor Dining',
      'Steak',
      'Sunday Brunch Buffet',
      'Igloo Dining',
      'Romantic Restaurant',
      'Bottomless Mimosas',
      'Breakfast and Brunch Restaurants',
      'Gluten Free Restaurants',
      'Birthday Dinner',
      'Mimosa',
      'Foodie Restaurants',
      'Prime Rib',
      'Restaurants for Large Groups',
      'Bar and Grill',
      'Trendy Restaurant',
      'Restaurants Outdoor Seating',
      'Dog Friendly Restaurants',
      'Restaurants With Private Dining Rooms',
      'Hot and New Restaurants',
      'Beef Wellington',
      'Rehearsal Dinner',
      'Happy Hour Specials',
      'Casual Dining',
      'Pancakes',
      'Michelin Star Restaurant',
      'Healthy Restaurant',
      'Restaurants Open Monday',
      'Rooftop Restaurant',
      'Restaurants Open Now',
      'Cocktails',
      'Valentines Dinner',
      'Espresso Martini',
      'American',
      'Organic Restaurant',
      'Keto Friendly Restaurants',
      'Nice Restaurant',
      'Most Expensive Restaurant',
      'Monday Night Dinner Specials',
      'Small Plates',
      'Group Dining',
      'Cioppino',
      'French Restaurant',
      'Dinner With a View',
      'Special Occasion Restaurant',
      'Special Occasion Dinner',
      'Beef Tartare',
      'Dinner Reservations',
      'Steak and Lobster',
      'Tapas/Small Plates',
      'New American Restaurant',
      'Casual Dinner',
      'Restaurants With Private Rooms',
      'Ribeye',
      'American Food',
      'Gastropubs',
      'Private Dining',
      'Quiet Restaurant',
      'Prix Fixe Dinner',
      'Fancy Dinner',
      'Anniversary Dinner',
      'Fancy Dinner Restaurant',
      'Private Party Room',
      'Group Dinner',
      'Steakhouse Restaurants',
      'Romantic Restaurants With a View',
      'Graduation Dinner',
      'Romantic Dinner',
      'Steak and Seafood',
      'Large Group Dining',
      'Valentines Day Dinner',
      'Private Room Dining',
      'Tapas',
      'Restaurants Business Dinner',
      'Restaurants Birthday Dinner',
      'Birthday Brunch',
      'Paella',
      'Baby Shower Restaurant',
      'Restaurants With Views',
      'High End Dining',
      'Business Lunch',
      'Bottomless Mimosa Brunch',
      'Bridal Shower Brunch',
      'Private Room Brunch',
      'Baby Shower Restaurant',
      'Wedding Rehearsal Dinner',
      'Brunch Buffet',
      'Restaurants With Private Room',
      'Restaurants With Private Party Rooms',
      'Private Dining Room',
      'Restaurants With Party Rooms',
      'Private Room',
      'Large Group Dinner',
      'Restaurants With Banquet Rooms',
      'Fancy Restaurant',
      'Steak House',
      'Upscale Restaurants',
      'Steakhouse',
      'Bottomless Brunch',
      'Outdoor Bar',
      'Family Restaurant',
      'Drinks and Appetizers',
      'Speakeasy Bars',
      'Dinner Restaurant',
      'Trendy Restaurants',
      'Patio Dining',
      'Romantic Anniversary Dinner',
      'Bar Restaurant',
      'Romantic Restaurants With a View',
      'Espresso Martini',
    ],
  },
  {
    id: 'equipment-rental',
    label: 'Equipment & Rental',
    vendorCategory: 'rentals',
    subcategories: [
      'Audio Video Installation',
      'Production Rentals',
      'Party Equipment Rentals',
      'Sound System Rental',
      'DJ Equipment Rental',
      'Entertainment',
      'Outdoor Movies',
      'Camera Rental',
      'Halls for Rent',
      'Banquet Halls',
      'Cheap Banquet Halls',
      'Dance Floor Rental',
      'Quinceanera Venue',
      'Karaoke Rental',
      'Sweet 16 Party Venues',
      'Furniture Rental',
      'Party Venues',
      'High Fidelity Audio Equipment',
      'Small Party Hall Rentals',
      'Cheap Halls for Rent',
      'DJ Equipment',
      'Projector Repair',
      'Party Rentals',
      'Party Rental Space',
      'Cheap Banquet Halls for Rent',
      'Dinnerware Rental',
      'Mechanical Bull',
      'Event Space',
      'Sound System',
      'Canopy & Tent Rental',
      'Electronic Parts',
      'Props',
      'Events',
      'Electronics Supply',
      'Fundraising Events',
      'Linen Rental',
      'Rental',
      'Audio Visual',
      'Party',
      'Wedding Planner',
      'Karaoke Store',
      'Party Halls',
      'Speaker Rental',
      'Prom Venues',
      'Lighting Rental',
      'Rooftop Venue',
      'Bar Mitzvah Venues',
      'Computer Rental',
      'Stage Rentals',
      'Chocolate Fountain',
      'Event Planning Companies',
    ],
  },
  {
    id: 'activities-entertainment',
    label: 'Activities & Entertainment',
    vendorCategory: 'bachelorette_activity',
    subcategories: [
      'Balloon Services',
      'Magicians',
      'Musicians',
      'Karaoke',
      'Comedy Clubs',
      'Jazz Club',
      'Trivia Night',
      'Open Mic',
    ],
  },
  {
    id: 'live-bands',
    label: 'Live Bands',
    vendorCategory: 'wedding_band',
    subcategories: [
      'Wedding Band',
      'Live Music',
      'Cover Band',
      'Jazz Band',
      'String Quartet',
      'Mariachi',
    ],
  },
  {
    id: 'photo-booths',
    label: 'Photo Booths',
    vendorCategory: 'photo_booth',
    subcategories: [
      'Photo Booth Rentals',
      'Open Air Photo Booth',
      'Digital Photo Booth',
      'Green Screen Photo Booth',
      'GIF Booth',
      '360 Photo Booth',
    ],
  },
  {
    id: 'transportation',
    label: 'Transportation',
    vendorCategory: 'transportation',
    subcategories: [
      'Party Bus',
      'Limo Service',
      'Wedding Shuttle',
      'Airport Transfer',
      'Vintage Car Rental',
      'Trolley Rental',
    ],
  },
  {
    id: 'videography',
    label: 'Videography',
    vendorCategory: 'videography',
    subcategories: [
      'Wedding Videographer',
      'Event Videography',
      'Drone Videography',
      'Same Day Edit',
      'Documentary Style',
    ],
  },
  {
    id: 'photography',
    label: 'Photography',
    vendorCategory: 'photography',
    subcategories: [
      'Wedding Photographer',
      'Portrait Photography',
      'Event Photography',
      'Engagement Photos',
      'Boudoir Photography',
    ],
  },
  {
    id: 'catering',
    label: 'Catering',
    vendorCategory: 'catering',
    subcategories: [
      'Caterers',
      'Wedding Catering',
      'Party Catering',
      'Corporate Catering',
      'BBQ Catering',
      'Small Party Catering',
      'Bartender Services',
      'Bartenders',
    ],
  },
  {
    id: 'florists',
    label: 'Florists',
    vendorCategory: 'florist',
    subcategories: [
      'Floral Designers',
      'Wedding Flowers',
      'Event Florals',
      'Flower Delivery',
      'Bridal Bouquets',
      'Ceremony Arrangements',
    ],
  },
  {
    id: 'decor-rentals',
    label: 'Decor & Rentals',
    vendorCategory: 'decor_rentals',
    subcategories: [
      'Party Decorations',
      'Event Design',
      'Table Settings',
      'Chair And Table Rentals',
      'Linen Rental',
      'Dinnerware Rental',
      'Props',
      'Dance Floor Rental',
      'Canopy & Tent Rental',
    ],
  },
  {
    id: 'jewelers',
    label: 'Jewelers',
    vendorCategory: 'jeweler',
    subcategories: [
      'Engagement Rings',
      'Wedding Bands',
      'Custom Jewelry',
      'Jewelry Repair',
    ],
  },
  {
    id: 'hair-makeup',
    label: 'Hair & Makeup',
    vendorCategory: 'makeup_hair',
    subcategories: [
      'Bridal Hair',
      'Bridal Makeup',
      'Hair Styling',
      'Makeup Artist',
      'Bridal Party Hair & Makeup',
      'On-Location Styling',
    ],
  },
  {
    id: 'officiants',
    label: 'Officiants',
    vendorCategory: 'officiant',
    subcategories: [
      'Wedding Officiant',
      'Non-Denominational',
      'Interfaith Officiant',
      'Civil Celebrant',
    ],
  },
  {
    id: 'bakeries-cakes',
    label: 'Bakeries & Cakes',
    vendorCategory: 'bakery',
    subcategories: [
      'Wedding Cakes',
      'Custom Cakes',
      'Cupcakes',
      'Cake Tasting',
      'Dessert Bars',
      'Custom Cookies',
    ],
  },
  {
    id: 'lighting-av',
    label: 'Lighting & AV',
    vendorCategory: 'lighting_av',
    subcategories: [
      'Audio Video Installation',
      'Event Lighting',
      'Sound System',
      'Sound System Rental',
      'DJ Equipment',
      'Lighting Rental',
      'Audio Visual',
      'Speaker Rental',
    ],
  },
  {
    id: 'stationery',
    label: 'Stationery',
    vendorCategory: 'stationery',
    subcategories: [
      'Wedding Invitations',
      'Save the Dates',
      'Day-Of Stationery',
      'Custom Design',
    ],
  },
  {
    id: 'invitations-print',
    label: 'Invitations & Print',
    vendorCategory: 'invitations_print',
    subcategories: [
      'Wedding Invitations',
      'Custom Invitations',
      'Letterpress',
      'Digital Printing',
      'Calligraphy',
    ],
  },
  {
    id: 'wellness-spa',
    label: 'Wellness & Spa',
    vendorCategory: 'wellness',
    subcategories: [
      'Spa Services',
      'Couples Massage',
      'Bridal Party Spa Day',
      'Wellness Retreats',
    ],
  },
  {
    id: 'wine-spirits',
    label: 'Wine & Spirits',
    vendorCategory: 'wine_spirits',
    subcategories: [
      'Wineries',
      'Wine Tasting',
      'Craft Cocktails',
      'Brewery Tour',
      'Distillery Tour',
    ],
  },
  {
    id: 'dress-attire',
    label: 'Dress & Attire',
    vendorCategory: 'dress_attire',
    subcategories: [
      'Wedding Dresses',
      'Bridal Boutiques',
      'Tuxedo Rental',
      'Bridesmaid Dresses',
      'Alterations',
    ],
  },
  {
    id: 'favors-gifts',
    label: 'Favors & Gifts',
    vendorCategory: 'favors_gifts',
    subcategories: [
      'Wedding Favors',
      'Custom Gifts',
      'Gift Baskets',
      'Party Favors',
    ],
  },
  {
    id: 'hotels-lodging',
    label: 'Hotels & Lodging',
    vendorCategory: 'hotel_accommodations',
    subcategories: [
      'Hotels',
      'Bed & Breakfast',
      'Boutique Hotels',
      'Group Room Blocks',
      'Wedding Party Accommodations',
    ],
  },
  {
    id: 'honeymoon-travel',
    label: 'Honeymoon & Travel',
    vendorCategory: 'honeymoon_travel',
    subcategories: [
      'Honeymoon Packages',
      'Destination Wedding',
      'Travel Agent',
      'All-Inclusive Resorts',
    ],
  },
]

// Location data
export const NEARBY_CITIES: LocationSection = {
  id: 'nearby-cities',
  label: 'Nearby Cities',
  items: [
    'Appleton WI',
    'Arlington Heights IL',
    'Brookfield WI',
    'Elgin IL',
    'Evanston IL',
    'Fond Du Lac WI',
    'Green Bay WI',
    'Janesville WI',
    'Kenosha WI',
    'Lake County IL',
    'Northbrook IL',
    'Oshkosh WI',
    'Outagamie County WI',
    'Racine WI',
    'Schaumburg IL',
    'Sheboygan WI',
    'Waukesha WI',
    'Wausau WI',
    'West Bend WI',
    'West Milwaukee WI',
  ],
}

export const NEIGHBORHOODS: LocationSection = {
  id: 'neighborhoods',
  label: 'Milwaukee Neighborhoods',
  items: [
    'Avenues West',
    "Brewer's Hill",
    'Downtown',
    'Historic Third Ward',
    'Jones Island',
    'Lower East Side',
    'Midtown',
    'Mitchell Park',
    'Sherman Park',
    "Walker's Point",
  ],
}

export const BARS_NEAR_LANDMARKS: LocationSection = {
  id: 'bars-near-landmarks',
  label: 'Bars Near Landmarks',
  items: [
    'Bars Near Holler Park',
    'Bars Near South Shore Park',
    'Bars Near Basilica of St. Josaphat',
    'Bars Near Kosciuszko Park',
    'Bars Near Grant Market',
    'Bars Near Milwaukee Brewing Company',
    'Bars Near Harley-Davidson Museum',
    'Bars Near Historic Third Ward',
    'Bars Near Henry Maier Festival Park',
    'Bars Near Milwaukee Public Market',
  ],
}

// Event types filter
export const EVENT_TYPES: FilterSection = {
  id: 'event-types',
  label: 'Event Types',
  items: [
    'Ceremony',
    'Class Reunion',
    'Fundraiser',
    'Party',
    'Prom/School Dance',
    'Silent Disco',
    'Wedding',
  ],
}

// Service category filters
export const SERVICE_CATEGORIES: FilterSection = {
  id: 'service-categories',
  label: 'Service Categories',
  items: [
    'Bartending',
    'Catering',
    'Equipment Rental',
    'Event Management',
    'Event Planning',
    'Full-service Event Planning and Execution',
    'Venue Rental',
  ],
}

// Amenities/Features filters
export const AMENITIES: FilterSection = {
  id: 'amenities',
  label: 'Amenities & Features',
  items: [
    'Outdoor Seating',
    'Good for Lunch',
    'Good for Kids',
    'Good for Groups',
    'Dogs Allowed',
    'Full Bar',
    'Good for Brunch',
    'Takes Reservations',
    'Good for Breakfast',
    'Accepts Apple Pay',
    'Accepts Cryptocurrency',
    'Accepts Credit Cards',
    'Open to All',
    'By Appointment Only',
    'Coat Check',
    'Flower Delivery',
    'Gender Neutral Restrooms',
    'Has TV',
    'Hot and New',
    'Service Booking Enabled',
    'Offers Military Discount',
    'Request a Quote',
    'Open 24 Hours',
    'Online Booking',
    'Waiter Service',
    'Wheelchair Accessible',
    'Beer & Wine Only',
    'Good For Happy Hour',
    'Good for Dessert',
    'Good for Late Night',
    'Music: DJ',
    'Music: Jukebox',
    'Music: Karaoke',
    'Music: Live',
    'Street Parking',
    'Garage Parking',
    'Valet Parking',
    'Private Lot Parking',
    'Validated Parking',
    'Free Wi-Fi',
    'Paid Wi-Fi',
  ],
}

// Other vendor categories (brief listing)
export const OTHER_VENDOR_CATEGORIES: FilterSection = {
  id: 'other-vendor-categories',
  label: 'Other Vendor Types',
  items: [
    'Balloon Services',
    'Bartenders',
    'Caterers',
    'DJs',
    'Floral Designers',
    'Hotels',
    'Magicians',
    'Musicians',
    'Officiants',
    'Party & Event Planning',
    'Party Equipment Rentals',
    'Party Supplies',
    'Photo Booth Rentals',
    'Photographers',
    'Venues & Event Spaces',
    'Videographers',
    'Wedding Chapels',
    'Wedding Planning',
  ],
}

// Helper: find which CategorySection a VendorCategory belongs to
export function findCategorySection(vendorCategory: VendorCategory): CategorySection | undefined {
  return DIRECTORY_CATEGORIES.find(c => c.vendorCategory === vendorCategory)
}

// Helper: get all subcategories as a flat array for search
export function getAllSubcategories(): string[] {
  const all: string[] = []
  DIRECTORY_CATEGORIES.forEach(section => {
    section.subcategories.forEach(sub => {
      if (!all.includes(sub)) all.push(sub)
    })
  })
  return all.sort((a, b) => a.localeCompare(b))
}
