export interface NeighborhoodArea {
  id: string
  label: string
  neighborhoods: string[]
}

export const NEIGHBORHOOD_AREAS: NeighborhoodArea[] = [
  {
    id: 'downtown',
    label: 'Downtown & Central',
    neighborhoods: [
      'Downtown',
      'East Town',
      'Westown',
      'Historic Third Ward',
      'Juneau Town',
      'Cathedral Square',
      'Yankee Hill',
      'Park East',
      'MacArthur Square',
      'Hillside',
      'Bronzeville',
      'Avenues West',
      'Plankinton Arc',
      'Grand Avenue',
      'Central Business District',
    ],
  },
  {
    id: 'east-side',
    label: 'East Side',
    neighborhoods: [
      'Lower East Side',
      'Brady Street',
      'North Point',
      'Lake Park',
      'Downer Woods',
      'Cambridge Woods',
      'Murray Hill',
      'Kenilworth',
      'Oakland Avenue',
      'Farwell Avenue',
      'Prospect Avenue',
      'Newberry Boulevard',
      'Water Tower District',
      'UWM Area',
      'East Side',
    ],
  },
  {
    id: 'south-side',
    label: 'South Side',
    neighborhoods: [
      'Bay View',
      "Walker's Point",
      'Lincoln Village',
      'Polonia',
      'Southgate',
      'Wilson Park',
      'Jackson Park',
      'Garden District',
      'Clarke Square',
      'Muskego Way',
      'Forest Home Hills',
      'Baran Park',
      'Humboldt Park',
      'Morgandale',
      'Layton Park',
      'South Point',
    ],
  },
  {
    id: 'west-side',
    label: 'West Side',
    neighborhoods: [
      'Washington Heights',
      'Story Hill',
      'Grandview',
      'Concordia',
      'Cold Spring Park',
      'Miller Valley',
      'Merrill Park',
      'Metcalfe Park',
      'Martin Drive',
      'Enderis Park',
      'Washington Park',
      'Piggsville',
      'Halyard Park',
      'Midtown',
      'Valley Park',
    ],
  },
  {
    id: 'north-side',
    label: 'North Side',
    neighborhoods: [
      'Riverwest',
      'Harambee',
      "Brewers' Hill",
      'Williamsburg Heights',
      'Rufus King',
      'Garden Homes',
      'Granville',
      'Thurston Woods',
      'Old North Milwaukee',
      'Arlington Heights',
      'Franklin Heights',
      'Westlawn',
      'Uptown',
      'Parklawn',
      'Carver Park',
      'North Division',
    ],
  },
]

// Flat array of all neighborhoods for easy consumption
export const ALL_NEIGHBORHOODS: string[] = NEIGHBORHOOD_AREAS.flatMap(
  (a) => a.neighborhoods
)

// Nearby cities for extended search
export const NEARBY_CITIES: string[] = [
  'Wauwatosa',
  'West Allis',
  'Brookfield',
  'Mequon',
  'Shorewood',
  'Whitefish Bay',
  'Glendale',
  'Brown Deer',
  'River Hills',
  'Fox Point',
  'Bayside',
  'Cudahy',
  'South Milwaukee',
  'St. Francis',
  'Oak Creek',
  'Franklin',
  'Greendale',
  'Hales Corners',
  'Greenfield',
  'West Milwaukee',
  'Waukesha',
  'New Berlin',
  'Muskego',
  'Pewaukee',
  'Menomonee Falls',
  'Germantown',
  'Cedarburg',
  'Grafton',
  'Port Washington',
  'Racine',
  'Kenosha',
  'Sheboygan',
  'Madison',
  'Appleton',
  'Green Bay',
]
