/**
 * Surface occasion/type data — auto-fills the "What" dropdown per surface.
 * Source: On Page Top Nav spec (user-provided doc).
 */

export interface SurfaceOption {
  label: string
  value: string
}

export const SURFACE_DATA: Record<string, {
  title: string
  subtitle: string
  icon: string
  whatOptions: SurfaceOption[]
  whatLabel: string
  whatPlaceholder: string
  example: string
  heroImage: string
  heroCopy: string
}> = {
  services: {
    title: 'Concierge',
    subtitle: 'Browse concierge & planning professionals',
    icon: 'concierge',
    whatLabel: 'Service',
    whatPlaceholder: 'Select service type',
    example: 'Wedding planners available everywhere',
    heroImage: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&q=80&w=1200',
    heroCopy: 'Expert planners for every occasion, everywhere.',
    whatOptions: [
      { label: 'Wedding Planner', value: 'wedding-planner' },
      { label: 'Corporate Event Planner', value: 'corporate-event-planner' },
      { label: 'Gala Event Planner', value: 'gala-event-planner' },
      { label: 'Destination Event Planner', value: 'destination-event-planner' },
      { label: 'Adult Birthday Party Planner', value: 'adult-birthday-planner' },
      { label: 'Kids Birthday Party Planner', value: 'kids-birthday-planner' },
      { label: 'Bar & Bat Mitzvah Planner', value: 'mitzvah-planner' },
      { label: 'Baby Shower Planner', value: 'baby-shower-planner' },
      { label: 'Travel Agent', value: 'travel-agent' },
      { label: 'Vacation Rental Agent', value: 'vacation-rental-agent' },
    ],
  },
  plan: {
    title: 'Plan',
    subtitle: 'Direct occasion-type planning',
    icon: 'event_note',
    whatLabel: 'Occasion',
    whatPlaceholder: 'Type your occasion (e.g., Birthday)',
    example: '"Birthday in Hong Kong" / "Bachelorette in Texas"',
    heroImage: 'https://images.unsplash.com/photo-1530023367847-a683933f4172?auto=format&fit=crop&q=80&w=1200',
    heroCopy: 'Tell us your occasion and destination. We handle the rest.',
    whatOptions: [
      { label: 'Birthday', value: 'birthday' },
      { label: 'Bachelorette', value: 'bachelorette' },
      { label: 'Bachelor', value: 'bachelor' },
      { label: 'Wedding Reception', value: 'wedding-reception' },
      { label: 'Anniversary', value: 'anniversary' },
      { label: 'Corporate Event', value: 'corporate-event' },
      { label: 'Graduation Party', value: 'graduation-party' },
      { label: 'Engagement Party', value: 'engagement-party' },
      { label: 'Baby Shower', value: 'baby-shower' },
      { label: 'Gala', value: 'gala' },
      { label: 'Photo Shoot', value: 'photo-shoot' },
      { label: 'Workshop', value: 'workshop' },
      { label: 'Meeting', value: 'meeting' },
      { label: 'Live Music', value: 'live-music' },
      { label: 'Video Shoot', value: 'video-shoot' },
      { label: 'Music Video', value: 'music-video' },
      { label: 'Bridal Shower', value: 'bridal-shower' },
      { label: 'Pop-up', value: 'pop-up' },
      { label: 'Film Shoot', value: 'film-shoot' },
    ],
  },
  'things-to-do': {
    title: 'Things to Do',
    subtitle: 'Browse local activities',
    icon: 'explore',
    whatLabel: 'Activity',
    whatPlaceholder: 'Select activity type',
    example: '"What\'s happening this weekend?"',
    heroImage: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&q=80&w=1200',
    heroCopy: 'Discover what\'s happening near you.',
    whatOptions: [
      { label: 'Art Show', value: 'art-show' },
      { label: 'Climbing Wall', value: 'climbing-wall' },
      { label: 'Happy Hour', value: 'happy-hour' },
      { label: 'Boats & Water Activities', value: 'boats-water' },
      { label: 'All Activities', value: 'all' },
    ],
  },
  'food-drink': {
    title: 'Food & Drink',
    subtitle: 'Browse restaurants, catering, dining',
    icon: 'restaurant',
    whatLabel: 'Dining',
    whatPlaceholder: 'Select dining type',
    example: '"Where should we eat?"',
    heroImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=1200',
    heroCopy: 'Find the perfect table for your occasion.',
    whatOptions: [
      { label: 'Dining', value: 'dining' },
      { label: 'Fine Dining', value: 'fine-dining' },
      { label: 'Casual Dining', value: 'casual-dining' },
      { label: 'Catering', value: 'catering' },
      { label: 'Bars & Pubs', value: 'bars-pubs' },
      { label: 'Coffee & Cafes', value: 'coffee-cafes' },
    ],
  },
  'live-shows': {
    title: 'Live Shows',
    subtitle: 'Browse concerts, sports, theater, comedy',
    icon: 'theater_comedy',
    whatLabel: 'Show',
    whatPlaceholder: 'Select show type',
    example: '"I want to see a show"',
    heroImage: 'https://images.unsplash.com/photo-1505156868577-294f3c54a1de?auto=format&fit=crop&q=80&w=1200',
    heroCopy: 'Concerts, sports, theater, and comedy — all in one place.',
    whatOptions: [
      { label: 'NBA', value: 'nba' },
      { label: 'NFL', value: 'nfl' },
      { label: 'MLB', value: 'mlb' },
      { label: 'NHL', value: 'nhl' },
      { label: 'Concerts', value: 'concerts' },
      { label: 'Theater', value: 'theater' },
      { label: 'Comedy', value: 'comedy' },
      { label: 'Broadway', value: 'broadway' },
      { label: ' Festivals', value: 'festivals' },
    ],
  },
  travel: {
    title: 'Travel',
    subtitle: 'Browse places to stay, flights, cars, destinations',
    icon: 'flight',
    whatLabel: 'Travel',
    whatPlaceholder: 'Select travel type',
    example: '"We need a place to stay"',
    heroImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=1200',
    heroCopy: 'Hotels, rentals, flights, and destinations for your trip.',
    whatOptions: [
      { label: 'Places to Stay', value: 'places-to-stay' },
      { label: 'Hotels', value: 'hotels' },
      { label: 'Vacation Rentals', value: 'vacation-rentals' },
      { label: 'Flights', value: 'flights' },
      { label: 'Car Rental', value: 'car-rental' },
      { label: 'Destinations', value: 'destinations' },
      { label: 'Group Trip', value: 'group-trip' },
    ],
  },
  party: {
    title: 'Party',
    subtitle: 'Browse by party type',
    icon: 'celebration',
    whatLabel: 'Party',
    whatPlaceholder: 'Select party type',
    example: 'Plan your celebration',
    heroImage: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&q=80&w=1200',
    heroCopy: 'Bachelorette, birthday, holiday party — find everything for your celebration.',
    whatOptions: [
      { label: 'Bachelorette', value: 'bachelorette' },
      { label: 'Bachelor', value: 'bachelor' },
      { label: 'Birthday', value: 'birthday' },
      { label: 'Group Trip', value: 'group-trip' },
      { label: 'New Year\'s Eve', value: 'new-years-eve' },
      { label: 'Thanksgiving', value: 'thanksgiving' },
      { label: 'Holiday Party', value: 'holiday-party' },
      { label: 'Dinner Party', value: 'dinner-party' },
      { label: 'Karaoke Bar', value: 'karaoke-bar' },
      { label: 'Elopement Party', value: 'elopement-party' },
      { label: 'Engagement Party', value: 'engagement-party' },
      { label: 'Baby Shower', value: 'baby-shower' },
      { label: 'Graduation Party', value: 'graduation-party' },
    ],
  },
  spaces: {
    title: 'Spaces',
    subtitle: 'Browse unique venues & spaces',
    icon: 'domain',
    whatLabel: 'Space',
    whatPlaceholder: 'Select space type',
    example: '"I need a space for my photo shoot / workshop / wedding"',
    heroImage: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&q=80&w=1200',
    heroCopy: 'Unique venues for every occasion and activity.',
    whatOptions: [
      { label: 'Wedding Reception', value: 'wedding-reception' },
      { label: 'Restaurants', value: 'restaurants' },
      { label: 'Hotels', value: 'hotels' },
      { label: 'Museums', value: 'museums' },
      { label: 'Outdoor', value: 'outdoor' },
      { label: 'Resorts', value: 'resorts' },
      { label: 'Boats', value: 'boats' },
      { label: 'Theaters', value: 'theaters' },
      { label: 'Farms', value: 'farms' },
      { label: 'Banquet Hall', value: 'banquet-hall' },
      { label: 'Wineries', value: 'wineries' },
      { label: 'Country Clubs', value: 'country-clubs' },
      { label: 'Estates', value: 'estates' },
      { label: 'Mansions', value: 'mansions' },
      { label: 'Meeting Spaces', value: 'meeting-spaces' },
      { label: 'Waterfront Venues', value: 'waterfront-venues' },
      { label: 'Rooftop', value: 'rooftop' },
      { label: 'Auditorium', value: 'auditorium' },
      { label: 'Content House', value: 'content-house' },
      { label: 'Cottage', value: 'cottage' },
    ],
  },
  vendors: {
    title: 'Vendors',
    subtitle: 'Browse vendor services & equipment',
    icon: 'storefront',
    whatLabel: 'Vendor',
    whatPlaceholder: 'Select vendor type',
    example: 'Find the right vendor for your occasion',
    heroImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&q=80&w=1200',
    heroCopy: 'DJs, photographers, caterers, and more — vetted and ready to book.',
    whatOptions: [
      { label: 'DJ', value: 'dj' },
      { label: 'Photographer', value: 'photographer' },
      { label: 'Videographer', value: 'videographer' },
      { label: 'Caterer', value: 'caterer' },
      { label: 'Florist', value: 'florist' },
      { label: 'Live Music', value: 'live-music' },
      { label: 'Entertainer', value: 'entertainer' },
      { label: 'Officiant', value: 'officiant' },
      { label: 'Event Planner', value: 'event-planner' },
      { label: 'Event Staffing', value: 'event-staffing' },
      { label: 'Bartenders', value: 'bartenders' },
      { label: 'Wait Staff', value: 'wait-staff' },
      { label: 'Security', value: 'security' },
      { label: 'Valet Parking', value: 'valet-parking' },
      { label: 'Transportation', value: 'transportation' },
      { label: 'Party Equipment Rental', value: 'party-equipment-rental' },
      { label: 'Audio Visual Equipment', value: 'av-equipment' },
      { label: 'Photo Booth', value: 'photo-booth' },
      { label: 'Tents & Tables', value: 'tents-tables' },
      { label: 'Lighting', value: 'lighting' },
      { label: 'Clowns & Magicians', value: 'clowns-magicians' },
    ],
  },
}

export const SURFACE_ROUTES = [
  { slug: 'services', label: 'Concierge', icon: 'concierge' },
  { slug: 'plan', label: 'Plan', icon: 'event_note' },
  { slug: 'things-to-do', label: 'Things to Do', icon: 'explore' },
  { slug: 'food-drink', label: 'Food & Drink', icon: 'restaurant' },
  { slug: 'live-shows', label: 'Live Shows', icon: 'theater_comedy' },
  { slug: 'travel', label: 'Travel', icon: 'flight' },
  { slug: 'party', label: 'Party', icon: 'celebration' },
  { slug: 'spaces', label: 'Spaces', icon: 'domain' },
  { slug: 'vendors', label: 'Vendors', icon: 'storefront' },
] as const
