// Error Code Constants per Part XI 11.2.2

export const ERROR_CODES = {
  // Authentication errors
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  
  // Authorization errors
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  NOT_A_VENDOR: 'NOT_A_VENDOR',
  NOT_VENDOR_OWNER: 'NOT_VENDOR_OWNER',
  NOT_A_MEMBER: 'NOT_A_MEMBER',
  
  // Inventory errors
  LOCATION_REQUIRED: 'LOCATION_REQUIRED',
  INVALID_CATEGORY: 'INVALID_CATEGORY',
  INVALID_PRICE: 'INVALID_PRICE',
  INVALID_METADATA: 'INVALID_METADATA',
  METADATA_INCOMPLETE: 'METADATA_INCOMPLETE',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  ITEM_UNAVAILABLE: 'ITEM_UNAVAILABLE',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  HAS_ACTIVE_RESERVATIONS: 'HAS_ACTIVE_RESERVATIONS',
  HAS_ACTIVE_CHECKOUT: 'HAS_ACTIVE_CHECKOUT',
  INVALID_QUANTITY: 'INVALID_QUANTITY',
  
  // Reservation errors
  INVALID_STATE: 'INVALID_STATE',
  CONFIRM_TOKEN_EXPIRED: 'CONFIRM_TOKEN_EXPIRED',
  
  // Cart errors
  EMPTY_CART: 'EMPTY_CART',
  CART_EXPIRED: 'CART_EXPIRED',
  INVENTORY_LOCK_FAILED: 'INVENTORY_LOCK_FAILED',
  
  // Vendor errors
  ALREADY_CLAIMED: 'ALREADY_CLAIMED',
  INVALID_CONTACT: 'INVALID_CONTACT',
  VENDOR_NOT_FOUND: 'VENDOR_NOT_FOUND',
  INVALID_CODE: 'INVALID_CODE',
  CLAIM_TOKEN_EXPIRED: 'CLAIM_TOKEN_EXPIRED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ALREADY_A_MEMBER: 'ALREADY_A_MEMBER',
  
  // Event errors
  INVALID_TIER_TYPE: 'INVALID_TIER_TYPE',
  INVALID_SALES_WINDOW: 'INVALID_SALES_WINDOW',
  EVENT_SOLD_OUT: 'EVENT_SOLD_OUT',
  INVALID_QR_TOKEN: 'INVALID_QR_TOKEN',
  ALREADY_CHECKED_IN: 'ALREADY_CHECKED_IN',
  OUTSIDE_CHECKIN_WINDOW: 'OUTSIDE_CHECKIN_WINDOW',
  
  // Search errors
  QUERY_TOO_SHORT: 'QUERY_TOO_SHORT',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  
  // General errors
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

export const HTTP_STATUS_CODES: Record<ErrorCode, number> = {
  // 400 Bad Request
  LOCATION_REQUIRED: 400,
  INVALID_CATEGORY: 400,
  INVALID_PRICE: 400,
  INVALID_METADATA: 400,
  METADATA_INCOMPLETE: 400,
  INVALID_QUANTITY: 400,
  INVALID_STATE: 400,
  EMPTY_CART: 400,
  CART_EXPIRED: 400,
  INVALID_CONTACT: 400,
  INVALID_CODE: 400,
  INVALID_TIER_TYPE: 400,
  INVALID_SALES_WINDOW: 400,
  INVALID_QR_TOKEN: 400,
  QUERY_TOO_SHORT: 400,
  INVALID_DATE_RANGE: 400,
  VALIDATION_ERROR: 400,
  
  // 401 Unauthorized
  NOT_AUTHENTICATED: 401,
  EMAIL_NOT_VERIFIED: 401,
  
  // 403 Forbidden
  NOT_AUTHORIZED: 403,
  NOT_A_VENDOR: 403,
  NOT_VENDOR_OWNER: 403,
  NOT_A_MEMBER: 403,
  
  // 404 Not Found
  ITEM_NOT_FOUND: 404,
  VENDOR_NOT_FOUND: 404,
  USER_NOT_FOUND: 404,
  NOT_FOUND: 404,
  
  // 409 Conflict
  USER_ALREADY_EXISTS: 409,
  ITEM_UNAVAILABLE: 409,
  INVALID_STATE_TRANSITION: 409,
  HAS_ACTIVE_RESERVATIONS: 409,
  HAS_ACTIVE_CHECKOUT: 409,
  INVENTORY_LOCK_FAILED: 409,
  ALREADY_CLAIMED: 409,
  CLAIM_TOKEN_EXPIRED: 409,
  CONFIRM_TOKEN_EXPIRED: 409,
  EVENT_SOLD_OUT: 409,
  ALREADY_CHECKED_IN: 409,
  OUTSIDE_CHECKIN_WINDOW: 409,
  ALREADY_A_MEMBER: 409,
  
  // 422 Unprocessable Entity
  // (mapped to 400 for now, can be separated if needed)
  
  // 429 Too Many Requests
  RATE_LIMIT_EXCEEDED: 429,
  
  // 500 Internal Server Error
  INTERNAL_ERROR: 500,
  
  // 503 Service Unavailable
  SERVICE_UNAVAILABLE: 503,
};

export function getHttpStatusForErrorCode(code: ErrorCode): number {
  return HTTP_STATUS_CODES[code] ?? 500;
}
