export interface LegalDoc {
  id: string;
  title: string;
  parentCategory: string;
  portals: ('consumer' | 'provider' | 'developer')[];
  purpose: string;
  lastUpdated: string;
  status: 'published' | 'pending';
  clauses?: { title: string; body: string }[];
}

export const PORTALS = [
  { id: 'consumer' as const, label: 'Consumer', description: 'Documents for Guests, Customers, Travelers, Event Attendees' },
  { id: 'provider' as const, label: 'Provider', description: 'Documents for Sellers, Hosts, Organizers, Vendors, Partners' },
  { id: 'developer' as const, label: 'Developer', description: 'Documents for API users, Integrators, Third-party developers' },
];

export const PARENT_CATEGORIES: { label: string; description: string }[] = [
  { label: 'Core Terms', description: 'Foundational platform documents.' },
  { label: 'Accounts & Roles', description: 'User role and participation agreements.' },
  { label: 'Commerce', description: 'Transaction and purchase policies.' },
  { label: 'Travel & Loyalty', description: 'Travel extras, loyalty, and premium programs.' },
  { label: 'Business Operations', description: 'Provider ecosystem and service terms.' },
  { label: 'Community', description: 'Content, community, and conduct standards.' },
  { label: 'Integrations', description: 'Partner and developer ecosystem.' },
  { label: 'Trust Center', description: 'Data protection, security, and compliance.' },
];

export const LEGAL_DOCS: LegalDoc[] = [
  // ===== CONSUMER: CORE TERMS =====
  {
    id: 'tos-unified',
    title: 'Terms of Service',
    parentCategory: 'Core Terms',
    portals: ['consumer'],
    purpose: 'Master Terms of Service for all users.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'privacy-policy-unified',
    title: 'Privacy Policy',
    parentCategory: 'Core Terms',
    portals: ['consumer', 'provider', 'developer'],
    purpose: 'Privacy policy covering all users across all services.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'cookie-policy-unified',
    title: 'Cookie Policy',
    parentCategory: 'Core Terms',
    portals: ['consumer', 'provider', 'developer'],
    purpose: 'Cookie policy for all users.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'sms-terms',
    title: 'Communications Policy',
    parentCategory: 'Core Terms',
    portals: ['consumer', 'provider'],
    purpose: 'Email, SMS, push notifications, and platform messaging rules.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'accessibility-statement',
    title: 'Accessibility Statement',
    parentCategory: 'Core Terms',
    portals: ['consumer'],
    purpose: 'Commitment to accessibility standards.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'dmca-policy',
    title: 'DMCA Policy',
    parentCategory: 'Core Terms',
    portals: ['consumer'],
    purpose: 'Copyright and intellectual property takedown procedures.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },

  // ===== CONSUMER: COMMERCE =====
  {
    id: 'standard-purchase-policy',
    title: 'Standard Purchase Policy',
    parentCategory: 'Commerce',
    portals: ['consumer'],
    purpose: 'Policy for purchasing standard (primary) tickets.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'resale-purchase-policy',
    title: 'Resale Purchase Policy',
    parentCategory: 'Commerce',
    portals: ['consumer'],
    purpose: 'Policy for purchasing resale tickets.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'travel-experiences-policy',
    title: 'Travel & Experiences Policy',
    parentCategory: 'Commerce',
    portals: ['consumer'],
    purpose: 'Policy for booking travel and experience packages.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'transfer-recipient-policy',
    title: 'Transfer Recipient Policy',
    parentCategory: 'Commerce',
    portals: ['consumer'],
    purpose: 'Policy for accepting ticket transfers.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'cancellation-refund-policy',
    title: 'Cancellation & Refund Policy',
    parentCategory: 'Commerce',
    portals: ['consumer'],
    purpose: 'Cancellation and refund policy for all services.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'cancelled-event-policy',
    title: 'Cancelled Event Policy',
    parentCategory: 'Commerce',
    portals: ['consumer'],
    purpose: 'Governs what happens when an event is cancelled, rescheduled, postponed, moved, or materially altered after you have purchased tickets or made a booking through the Planviry Platform. Covers all event categories (concerts, sporting events, theater, festivals, conferences), your rights and refund options, ticket insurance, resale and transferred tickets, VIP packages, notification process, time limits for claims, and event organizer responsibilities.',
    lastUpdated: 'January 2026',
    status: 'published',
  },

  // ===== CONSUMER: TRAVEL & LOYALTY =====
  {
    id: 'travel-insurance-policy',
    title: 'Travel Insurance Policy',
    parentCategory: 'Travel & Loyalty',
    portals: ['consumer'],
    purpose: 'Insurance options for travelers.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'group-travel-policy',
    title: 'Group Travel Policy',
    parentCategory: 'Travel & Loyalty',
    portals: ['consumer'],
    purpose: 'Governs group bookings (10+ travelers) and coordinated group travel arrangements made through the Planviry Platform, including leisure groups, corporate groups, educational groups, sports teams, destination weddings, and special interest groups.',
    lastUpdated: 'January 2026',
    status: 'published',
  },
  {
    id: 'loyalty-program-terms',
    title: 'Loyalty Program Terms',
    parentCategory: 'Travel & Loyalty',
    portals: ['consumer'],
    purpose: 'Governs the Planviry Loyalty Program (Free, Paid, Lifetime, Enterprise, Family plans), including enrollment, Points earning and redemption, tier qualification (Silver/Gold/Platinum/Diamond), VIP/Club Access benefits, expiration, fraud prevention, and program changes across the marketplace, insurance, transportation, dining, and retail ecosystem.',
    lastUpdated: 'January 2026',
    status: 'published',
  },
  {
    id: 'vip-club-access-terms',
    title: 'VIP/Club Access Program Terms',
    parentCategory: 'Travel & Loyalty',
    portals: ['consumer'],
    purpose: 'Governs the Planviry VIP/Club Access Program, a premium benefits program available to Platinum and Diamond tier Loyalty Program members and qualifying Paid Membership plan holders. Covers Club Access and Diamond VIP tiers, dedicated concierge service, complimentary upgrades, airport lounge access, checked bag, early check-in/late check-out, exclusive events, complimentary insurance, welcome amenities, priority support, partner benefits, benefit substitution, blackout dates, force majeure, digital credentials, capacity management, fraud prevention, and termination.',
    lastUpdated: 'January 2026',
    status: 'published',
  },

  // ===== CONSUMER: TRUST CENTER =====
  {
    id: 'biometric-privacy-notice',
    title: 'Biometric Privacy Notice',
    parentCategory: 'Trust Center',
    portals: ['consumer'],
    purpose: 'Biometric data collection and privacy.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'privacy-notices',
    title: 'Privacy Notices',
    parentCategory: 'Trust Center',
    portals: ['consumer'],
    purpose: 'Global framework and jurisdiction-specific privacy notices for 30+ jurisdictions including all US state privacy laws (CCPA/CPRA, VCDPA, CPA, CTDPA, UCPA, and 17 other state laws), GDPR/UK GDPR, and privacy laws for Canada, Brazil, Australia, Singapore, Japan, South Korea, India, Mexico, Argentina, South Africa, UAE, Saudi Arabia, Turkey, China, Thailand, Indonesia, Philippines, Malaysia, Israel, Vietnam, Hong Kong, and Nigeria. Includes data subject rights, automated decision-making, data retention, security governance, children privacy, cookie technologies, controller/processor roles, international transfers, sensitive data, biometric information, breach notification, government requests, complaints/appeals, and legitimate interest assessments.',
    lastUpdated: 'January 2026',
    status: 'published',
  },
  {
    id: 'payment-security-pci',
    title: 'Payment Security & PCI Compliance',
    parentCategory: 'Trust Center',
    portals: ['consumer'],
    purpose: 'Establishes the security requirements and compliance framework for payment card processing through the Planviry Platform, supporting PCI DSS v4.0 compliance. Covers the 12 core PCI DSS requirements, payment page security and e-skimming prevention, script management and integrity, data protection and encryption, access controls and MFA, network security, vulnerability management, logging and monitoring, incident response and breach notification, third-party service provider management, data retention and disposal, employee training, compliance validation, policy governance, and enforcement.',
    lastUpdated: 'January 2026',
    status: 'published',
  },
  {
    id: 'security-policy',
    title: 'Security Policy',
    parentCategory: 'Trust Center',
    portals: ['consumer', 'developer'],
    purpose: 'Establishes the information security requirements and controls for the protection of Planviry systems, data, and operations. Aligns with ISO 27001, NIST Cybersecurity Framework, and SOC 2. Covers information security management framework, risk management, asset classification, access control, personnel security, physical and environmental security, network and communications security, application and system development security, data security and encryption, vulnerability management, security monitoring and logging, incident response and business continuity, third-party and vendor security, compliance and audit, and policy governance.',
    lastUpdated: 'January 2026',
    status: 'published',
  },
  {
    id: 'ai-use-policy',
    title: 'AI Use Policy',
    parentCategory: 'Trust Center',
    portals: ['consumer', 'provider', 'developer'],
    purpose: 'Establishes the principles, requirements, and governance framework for the development, deployment, and use of artificial intelligence (AI) and machine learning (ML) systems within Planviry. Covers AI risk categories, roles and responsibilities, lifecycle governance, approval gates, AI inventory, permitted and prohibited uses, shadow AI prevention, data classification for AI, privacy, transparency, human oversight, automated decision appeals, explainability, accuracy metrics, bias and fairness, security threat model, prompt security, model risk management, AI supply chain, foundation models, third-party AI services, AI red teaming, incident response, copyright/IP, synthetic media and deepfakes, employee acceptable use, procurement, documentation, change management, logging, output retention, business continuity, cross-border processing, AI ethics review, AI register, data lineage, model validation independence, AI agent governance, model retirement, continuous improvement, regulatory change management, customer rights, AI governance, compliance and regulatory mapping, reporting and accountability, and policy governance.',
    lastUpdated: 'January 2026',
    status: 'published',
  },
  {
    id: 'data-processing-agreement',
    title: 'Data Processing Agreement',
    parentCategory: 'Trust Center',
    portals: ['provider', 'developer'],
    purpose: 'Data Processing Agreement (DPA) governing the processing of personal data by Planviry on behalf of providers and partners, including data subject rights, security measures, and sub-processor terms.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'data-deletion-retention',
    title: 'Data Deletion & Retention Policy',
    parentCategory: 'Trust Center',
    portals: ['consumer'],
    purpose: 'Policy for user data deletion and retention.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },

  // ===== PROVIDER: ACCOUNTS & ROLES =====
  {
    id: 'business-services-agreement',
    title: 'Business Services Agreement',
    parentCategory: 'Accounts & Roles',
    portals: ['provider'],
    purpose: 'Foundational agreement for Providers (General Terms + Selling on Planviry Service Terms).',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'selling-on-planviry-terms',
    title: 'Selling on Planviry Service Terms',
    parentCategory: 'Accounts & Roles',
    portals: ['provider'],
    purpose: 'Listing and selling services on Planviry.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'host-tos',
    title: 'Host Terms of Service',
    parentCategory: 'Accounts & Roles',
    portals: ['provider'],
    purpose: 'Terms for Hosts listing accommodations and venues.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'accommodation-fee-collection',
    title: 'Accommodation Fee Collection Agreement',
    parentCategory: 'Accounts & Roles',
    portals: ['provider'],
    purpose: 'Payment collection terms for Hosts.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'merchant-agreement',
    title: 'Merchant Agreement',
    parentCategory: 'Accounts & Roles',
    portals: ['provider'],
    purpose: 'Agreement for Event Organizers.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'partner-vendor-terms',
    title: 'Partner & Vendor Terms',
    parentCategory: 'Accounts & Roles',
    portals: ['provider'],
    purpose: 'Terms for partners and vendors.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'guest-tos',
    title: 'Guest Terms of Service',
    parentCategory: 'Accounts & Roles',
    portals: ['provider'],
    purpose: 'Understanding guest rights (cross-reference).',
    lastUpdated: 'January 2026',
    status: 'pending',
  },

  // ===== PROVIDER: BUSINESS OPERATIONS =====
  {
    id: 'program-policies',
    title: 'Program Policies',
    parentCategory: 'Business Operations',
    portals: ['provider'],
    purpose: 'All program policies for Providers.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'provider-rating',
    title: 'Provider Rating Policy',
    parentCategory: 'Business Operations',
    portals: ['provider'],
    purpose: 'How providers are rated and assessed.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'restricted-services',
    title: 'Restricted Services Policy',
    parentCategory: 'Business Operations',
    portals: ['provider'],
    purpose: 'Prohibited or restricted services.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'tax-policies',
    title: 'Tax Policies',
    parentCategory: 'Business Operations',
    portals: ['provider'],
    purpose: 'Tax calculation, collection, and remittance.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'fee-schedule-stripe',
    title: 'Fee Schedule',
    parentCategory: 'Business Operations',
    portals: ['provider'],
    purpose: 'Platform fees and payment processing fees.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'variable-fee-schedule',
    title: 'Variable Fee Schedule',
    parentCategory: 'Business Operations',
    portals: ['provider'],
    purpose: 'Category-specific fees.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'subscription-tiers-pricing',
    title: 'Subscription Tiers and Pricing',
    parentCategory: 'Business Operations',
    portals: ['provider'],
    purpose: 'Provider subscription plans.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'volume-discount-policy',
    title: 'Volume Discount Policy',
    parentCategory: 'Business Operations',
    portals: ['provider'],
    purpose: 'Volume-based discounts.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'promotional-fee-policy',
    title: 'Promotional Fee Policy',
    parentCategory: 'Business Operations',
    portals: ['provider'],
    purpose: 'Promotional fee periods.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },

  // ===== PROVIDER: COMMUNITY =====
  {
    id: 'acceptable-use-policy',
    title: 'Acceptable Use Policy',
    parentCategory: 'Community',
    portals: ['provider'],
    purpose: 'What providers may not do.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'community-guidelines-wedding',
    title: 'Community Guidelines',
    parentCategory: 'Community',
    portals: ['provider'],
    purpose: 'Expected provider behavior.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'content-guidelines-core',
    title: 'Content Guidelines',
    parentCategory: 'Community',
    portals: ['provider'],
    purpose: 'Formatting and quality standards for listings.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'acceptable-content-policy',
    title: 'Acceptable Content Policy',
    parentCategory: 'Community',
    portals: ['provider'],
    purpose: 'Prohibited content categories.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'rating-and-review-policy',
    title: 'Rating and Review Policy',
    parentCategory: 'Community',
    portals: ['provider'],
    purpose: 'Governs customer ratings, reviews, and feedback.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },

  // ===== PROVIDER: INTEGRATIONS =====
  {
    id: 'agent-policy',
    title: 'Agent Policy',
    parentCategory: 'Integrations',
    portals: ['provider', 'developer'],
    purpose: 'Third-party software and agent interaction rules.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'trademark-usage-policy',
    title: 'Trademark Usage Policy',
    parentCategory: 'Integrations',
    portals: ['provider'],
    purpose: 'Using Planviry brands and badges.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'intellectual-property-policy',
    title: 'Intellectual Property Policy',
    parentCategory: 'Integrations',
    portals: ['provider'],
    purpose: 'IP enforcement and protection.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },

  // ===== PROVIDER: TRUST CENTER (additional) =====
  {
    id: 'partner-disclosure-policy',
    title: 'Partner Disclosure Policy',
    parentCategory: 'Trust Center',
    portals: ['provider'],
    purpose: 'Disclosure requirements for partners.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'premier-host-program',
    title: 'Premier Host Program',
    parentCategory: 'Trust Center',
    portals: ['provider'],
    purpose: 'Search ranking program for qualifying Hosts.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },

  // ===== DEVELOPER: INTEGRATIONS =====
  {
    id: 'api-terms',
    title: 'API Terms of Use',
    parentCategory: 'Integrations',
    portals: ['developer'],
    purpose: 'Developer API access rules.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
  {
    id: 'advertising-services-terms',
    title: 'Advertising Services Terms',
    parentCategory: 'Integrations',
    portals: ['developer'],
    purpose: 'Ad integration rules.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },

  // ===== DEVELOPER: COMMUNITY =====
  {
    id: 'planviry-ads-guidelines',
    title: 'Ads Guidelines',
    parentCategory: 'Community',
    portals: ['developer'],
    purpose: 'Ad content rules.',
    lastUpdated: 'January 2026',
    status: 'pending',
  },
];

export function getDocById(id: string): LegalDoc | undefined {
  return LEGAL_DOCS.find((d) => d.id === id);
}
